In [1]:
"""
Chapter_5. Linear Algebra
参考
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
"""
import numpy as np

In [2]:
# Simple Array Operations==============
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
# [[ 1.  2.]
#  [ 3.  4.]]

print(a.transpose())
# array([[ 1.,  3.],
#        [ 2.,  4.]])

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]


In [3]:
print(np.linalg.inv(a))
# array([[-2. ,  1. ],
#        [ 1.5, -0.5]])

u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
print(u)
# array([[ 1.,  0.],
#        [ 0.,  1.]])

[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.  0.]
 [ 0.  1.]]


In [4]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

print(np.dot (j, j)) # matrix product
# array([[-1.,  0.],
#        [ 0., -1.]])

print(np.trace(u))  # trace
# 2.0

[[-1.  0.]
 [ 0. -1.]]
2.0


In [5]:
y = np.array([[5.], [7.]])
print(np.linalg.solve(a, y))
# array([[-3.],
#        [ 4.]])

print(np.linalg.eig(j))
# (array([ 0.+1.j,  0.-1.j]), array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
#        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))

[[-3.]
 [ 4.]]
(array([ 0.+1.j,  0.-1.j]), array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
       [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))
