In [1]:
"""
Chapter_1_3. The Basics(Universal Functions ~ Indexing, Slicing and Iterating)
参考
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
"""
import numpy as np

In [2]:
# Universal Functions==============
B = np.arange(3)
print(B)
# array([0, 1, 2])
print(np.exp(B))
# array([ 1.        ,  2.71828183,  7.3890561 ])
print(np.sqrt(B))
# array([ 0.        ,  1.        ,  1.41421356])
C = np.array([2., -1., 4.])
print(np.add(B, C))
# array([ 2.,  0.,  6.])

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]
[ 2.  0.  6.]


In [4]:
# Indexing, Slicing and Iterating=======
a = np.arange(10)**3
print(a)
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a[2])
# 8
print(a[2:5])
# array([ 8, 27, 64])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)
# array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])
print(a[ : :-1])                                 # reversed a
# array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]


In [5]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print(b)
# array([[ 0,  1,  2,  3],
#        [10, 11, 12, 13],
#        [20, 21, 22, 23],
#        [30, 31, 32, 33],
#        [40, 41, 42, 43]])
print(b[2,3])
# 23
print(b[0:5, 1])                       # each row in the second column of b
# array([ 1, 11, 21, 31, 41])
print(b[ : ,1])                        # equivalent to the previous example
# array([ 1, 11, 21, 31, 41])
print(b[1:3, : ])                      # each column in the second and third row of b
# array([[10, 11, 12, 13],
#        [20, 21, 22, 23]])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


In [6]:
print(b[-1])                                  # the last row. Equivalent to b[-1,:]
# array([40, 41, 42, 43])

[40 41 42 43]


In [7]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print(c.shape)
# (2, 2, 3)
print(c[1,...])                                   # same as c[1,:,:] or c[1]
# array([[100, 101, 102],
#        [110, 112, 113]])
print(c[...,2])                                   # same as c[:,:,2]
# array([[  2,  13],
#        [102, 113]])

(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [8]:
for row in b:
    print(row)
# [0 1 2 3]
# [10 11 12 13]
# [20 21 22 23]
# [30 31 32 33]
# [40 41 42 43]

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [9]:
for element in b.flat:
    print(element)

# 0
# 1
# 2
# 3
# 10
# 11
# 12
# 13
# 20
# 21
# 22
# 23
# 30
# 31
# 32
# 33
# 40
# 41
# 42
# 43

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
