In [1]:
"""
Chapter_2. Shape Manipulation
参考
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
"""
import numpy as np

In [2]:
# Changing the shape of an array=========
a = np.floor(10*np.random.random((3,4)))
print(a)
# array([[ 2.,  8.,  0.,  6.],
#        [ 4.,  5.,  1.,  1.],
#        [ 8.,  9.,  3.,  6.]])
print(a.shape)
# (3, 4)

[[ 6.  9.  6.  5.]
 [ 0.  2.  3.  7.]
 [ 5.  4.  3.  0.]]
(3, 4)


In [3]:
print(a.ravel())  # returns the array, flattened
# array([ 2.,  8.,  0.,  6.,  4.,  5.,  1.,  1.,  8.,  9.,  3.,  6.])
print(a.reshape(6,2))  # returns the array with a modified shape
# array([[ 2.,  8.],
#        [ 0.,  6.],
#        [ 4.,  5.],
#        [ 1.,  1.],
#        [ 8.,  9.],
#        [ 3.,  6.]])
print(a.T)  # returns the array, transposed
# array([[ 2.,  4.,  8.],
#        [ 8.,  5.,  9.],
#        [ 0.,  1.,  3.],
#        [ 6.,  1.,  6.]])
print(a.T.shape)
# (4, 3)
print(a.shape)
# (3, 4)

[ 6.  9.  6.  5.  0.  2.  3.  7.  5.  4.  3.  0.]
[[ 6.  9.]
 [ 6.  5.]
 [ 0.  2.]
 [ 3.  7.]
 [ 5.  4.]
 [ 3.  0.]]
[[ 6.  0.  5.]
 [ 9.  2.  4.]
 [ 6.  3.  3.]
 [ 5.  7.  0.]]
(4, 3)
(3, 4)


In [5]:
print(a)
# array([[ 2.,  8.,  0.,  6.],
#        [ 4.,  5.,  1.,  1.],
#        [ 8.,  9.,  3.,  6.]])
a.resize((2,6))
print(a)
# array([[ 2.,  8.,  0.,  6.,  4.,  5.],
#        [ 1.,  1.,  8.,  9.,  3.,  6.]])

[[ 6.  9.  6.  5.  0.  2.]
 [ 3.  7.  5.  4.  3.  0.]]
[[ 6.  9.  6.  5.  0.  2.]
 [ 3.  7.  5.  4.  3.  0.]]


In [6]:
print(a.reshape(3,-1))
# array([[ 2.,  8.,  0.,  6.],
#        [ 4.,  5.,  1.,  1.],
#        [ 8.,  9.,  3.,  6.]])

[[ 6.  9.  6.  5.]
 [ 0.  2.  3.  7.]
 [ 5.  4.  3.  0.]]


In [7]:
# Stacking together different arrays==========
a = np.floor(10*np.random.random((2,2)))
print(a)
# array([[ 8.,  8.],
#        [ 0.,  0.]])
b = np.floor(10*np.random.random((2,2)))
print(b)
# array([[ 1.,  8.],
#        [ 0.,  4.]])
print(np.vstack((a,b)))
# array([[ 8.,  8.],
#        [ 0.,  0.],
#        [ 1.,  8.],
#        [ 0.,  4.]])
print(np.hstack((a,b)))
# array([[ 8.,  8.,  1.,  8.],
#        [ 0.,  0.,  0.,  4.]])

[[ 5.  8.]
 [ 5.  3.]]
[[ 2.  1.]
 [ 3.  4.]]
[[ 5.  8.]
 [ 5.  3.]
 [ 2.  1.]
 [ 3.  4.]]
[[ 5.  8.  2.  1.]
 [ 5.  3.  3.  4.]]


In [8]:
from numpy import newaxis
print(np.column_stack((a,b)))   # With 2D arrays
# array([[ 8.,  8.,  1.,  8.],
#        [ 0.,  0.,  0.,  4.]])
a = np.array([4.,2.])
b = np.array([2.,8.])
print(a[:,newaxis])  # This allows to have a 2D columns vector
# array([[ 4.],
#        [ 2.]])
print(np.column_stack((a[:,newaxis],b[:,newaxis])))
# array([[ 4.,  2.],
#        [ 2.,  8.]])
print(np.vstack((a[:,newaxis],b[:,newaxis]))) # The behavior of vstack is different
# array([[ 4.],
#        [ 2.],
#        [ 2.],
#        [ 8.]])

[[ 5.  8.  2.  1.]
 [ 5.  3.  3.  4.]]
[[ 4.]
 [ 2.]]
[[ 4.  2.]
 [ 2.  8.]]
[[ 4.]
 [ 2.]
 [ 2.]
 [ 8.]]


In [9]:
print(np.r_[1:4,0,4])
# array([1, 2, 3, 0, 4])

[1 2 3 0 4]


In [10]:
# Splitting one array into several smaller ones
a = np.floor(10*np.random.random((2,12)))
print(a)
# array([[ 9.,  5.,  6.,  3.,  6.,  8.,  0.,  7.,  9.,  7.,  2.,  7.],
#        [ 1.,  4.,  9.,  2.,  2.,  1.,  0.,  6.,  2.,  2.,  4.,  0.]])
print(np.hsplit(a,3))   # Split a into 3
# [array([[ 9.,  5.,  6.,  3.],
#        [ 1.,  4.,  9.,  2.]]), array([[ 6.,  8.,  0.,  7.],
#        [ 2.,  1.,  0.,  6.]]), array([[ 9.,  7.,  2.,  7.],
#        [ 2.,  2.,  4.,  0.]])]
print(np.hsplit(a,(3,4)))   # Split a after the third and the fourth column
# [array([[ 9.,  5.,  6.],
#        [ 1.,  4.,  9.]]), array([[ 3.],
#        [ 2.]]), array([[ 6.,  8.,  0.,  7.,  9.,  7.,  2.,  7.],
#        [ 2.,  1.,  0.,  6.,  2.,  2.,  4.,  0.]])]

[[ 8.  9.  2.  8.  1.  3.  3.  0.  5.  3.  4.  9.]
 [ 2.  7.  8.  6.  1.  6.  4.  0.  1.  6.  8.  9.]]
[array([[ 8.,  9.,  2.,  8.],
       [ 2.,  7.,  8.,  6.]]), array([[ 1.,  3.,  3.,  0.],
       [ 1.,  6.,  4.,  0.]]), array([[ 5.,  3.,  4.,  9.],
       [ 1.,  6.,  8.,  9.]])]
[array([[ 8.,  9.,  2.],
       [ 2.,  7.,  8.]]), array([[ 8.],
       [ 6.]]), array([[ 1.,  3.,  3.,  0.,  5.,  3.,  4.,  9.],
       [ 1.,  6.,  4.,  0.,  1.,  6.,  8.,  9.]])]
