In [1]:
"""
Chapter_3. Copies and Views
参考
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
"""
import numpy as np

In [2]:
# No Copy at All=====================
a = np.arange(12)
b = a            # no new object is created
print(b is a)           # a and b are two names for the same ndarray object
# True
b.shape = 3,4    # changes the shape of a
print(a.shape)
# (3, 4)

True
(3, 4)


In [4]:
def f(x):
    print(id(x))

print(id(a))                           # id is a unique identifier of an object
# 148293216
f(a)
# 148293216

4393576848
4393576848


In [5]:
# View or Shallow Copy=================
c = a.view()
print(c is a)
# False
print(c.base is a)                        # c is a view of the data owned by a
# True
print(c.flags.owndata)
# False

c.shape = 2,6                      # a's shape doesn't change
print(a.shape)
(3, 4)
c[0,4] = 1234                      # a's data changes
print(a)
# array([[   0,    1,    2,    3],
#        [1234,    5,    6,    7],
#        [   8,    9,   10,   11]])

False
True
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [6]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print(a)
# array([[   0,   10,   10,    3],
#        [1234,   10,   10,    7],
#        [   8,   10,   10,   11]])

[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]


In [7]:
# Deep Copy
d = a.copy()                          # a new array object with new data is created
print(d is a)
# False
print(d.base is a)                           # d doesn't share anything with a
# False
d[0,0] = 9999
print(a)
# array([[   0,   10,   10,    3],
#        [1234,   10,   10,    7],
#        [   8,   10,   10,   11]])

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]
