In [1]:
"""
Chapter_1_2. The Basics(Printing Arrays ~ Basic Operations)
参考
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
"""
import numpy as np
from numpy import pi

In [2]:
# Printing Arrays==============
a = np.arange(6)                         # 1d array
print(a)
# [0 1 2 3 4 5]

b = np.arange(12).reshape(4,3)           # 2d array
print(b)
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]]

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
print(np.arange(10000))
# [   0    1    2 ..., 9997 9998 9999]

print(np.arange(10000).reshape(100,100))
# [[   0    1    2 ...,   97   98   99]
#  [ 100  101  102 ...,  197  198  199]
#  [ 200  201  202 ...,  297  298  299]
#  ...,
#  [9700 9701 9702 ..., 9797 9798 9799]
#  [9800 9801 9802 ..., 9897 9898 9899]
#  [9900 9901 9902 ..., 9997 9998 9999]]

[   0    1    2 ..., 9997 9998 9999]
[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [4]:
# Basic Operations================
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)
# array([0, 1, 2, 3])
c = a-b
print(c)
# array([20, 29, 38, 47])
print(b**2)
# array([0, 1, 4, 9])
print(10*np.sin(a))
# array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])
print(a<35)
# array([ True, True, False, False], dtype=bool)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [5]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A*B)                         # elementwise product
# array([[2, 0],
#        [0, 4]])
print(A.dot(B))                    # matrix product
# array([[5, 4],
#        [3, 4]])
print(np.dot(A, B))                # another matrix product
# array([[5, 4],
#        [3, 4]])

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [6]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print(a)
# array([[3, 3, 3],
#        [3, 3, 3]])
b += a
print(b)
# array([[ 3.417022  ,  3.72032449,  3.00011437],
#        [ 3.30233257,  3.14675589,  3.09233859]])

[[3 3 3]
 [3 3 3]]
[[ 3.5084616   3.47660058  3.26951565]
 [ 3.81208483  3.08906256  3.23180015]]


In [7]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print(b.dtype.name)
# 'float64'
c = a+b
print(c)
# array([ 1.        ,  2.57079633,  4.14159265])
print(c.dtype.name)
# 'float64'
d = np.exp(c*1j)
print(d)
# array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
#        -0.54030231-0.84147098j])
print(d.dtype.name)
# 'complex128'

float64
[ 1.          2.57079633  4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


In [8]:
a = np.random.random((2,3))
print(a)
# array([[ 0.18626021,  0.34556073,  0.39676747],
#        [ 0.53881673,  0.41919451,  0.6852195 ]])
print(a.sum())
# 2.5718191614547998
print(a.min())
# 0.1862602113776709
print(a.max())
# 0.6852195003967595

[[ 0.01508242  0.69065173  0.10851424]
 [ 0.95085134  0.54735791  0.96561459]]
3.2780722269
0.0150824177551
0.965614591237


In [9]:
b = np.arange(12).reshape(3,4)
print(b)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

print(b.sum(axis=0))                            # sum of each column
# array([12, 15, 18, 21])

print(b.min(axis=1))                            # min of each row
# array([0, 4, 8])

print(b.cumsum(axis=1))                         # cumulative sum along each row
# array([[ 0,  1,  3,  6],
#        [ 4,  9, 15, 22],
#        [ 8, 17, 27, 38]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
